# Generated by Django 5.1.4 on 2025-06-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('messaes', models.TextField()),
                ('chat_id', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('human', 'Human'), ('ai', 'AI')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FeedPost',
            fields=[
                ('post_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=200)),
                ('post_content', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
            ],
        ),
    ]
